### ISSUE TITLE
International keyboard support for the console key

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#11]
In gravit 0.5.1, The console line (^ ) for issuing commands manually
does not work with international keyboards anymore.

For example on a German keyboard, 
when pressing "z", it displays "y". 
Other keys like "?", ">" or "_" also give wrong characters.

(possibly caused by removing the event.key.keysym.unicode support from input.c)

**Comment by gak** [comment]
I was hoping that change wouldn't stuff up other keyboards. I removed it originally because it was causing problems in OS X.

**Comment by FrMo** [comment]
I have an idea how to fix this ... will try during this week.

**Comment by FrMo** [comment]
@gak: hotfix/11-console-input should fix the console input problem; cold you cross-check on MacOS and linux ?

https://github.com/gak/gravit/tree/hotfix/11-console-input

**Comment by FrMo** [comment]
fix tested by me on Windows and intel Linux (ubuntu).
@gak: please check OSX.

**Comment by gak** [comment]
@FrMo Will do.

**Comment by gak** [comment]
In OS X on my keyboard, the caret key ^ is on my keyboard as shift-6. It turns into a 6.

It's not a big problem as it's an unusual character to use in the console. The only reason I can think of using it is if you want a filename with it in it. I've created #58 for 0.5.1.

When I get around to testing the Linux build, and it's the same problem, I'll close off this issue so we can release.

**Comment by gak** [comment]
All good in Linux sans my previous bug.
