### ISSUE TITLE
Support for LUA 5.1.x

### ISSUE THREAD

**Issue by peti** [gak/gravit#16]
Gravit doesn't build with the latest version of LUA, apparently because of changes in the API.

**Comment by FrMo** [comment]
hi peti,
did you compile the latest version (0.5.1)? "it works for me" (tm), at least on windows.

I think there were two changes:
- Makefile : older releases needed **-llua -lualib** for linking, while some newer distributions have everything stuffed into one library **-llua5.1**. 
  -> try to replace -llua -llualib with -llua5.1
- lua.c: change the following lines in **int luaInit() {** :
  
  luaopen_base(state.lua);
  luaopen_io(state.lua);
  luaopen_table(state.lua);
  luaopen_string(state.lua);
  luaopen_math(state.lua);

to 
    luaL_openlibs(state.lua);
    luaopen_base(state.lua);
    luaopen_table(state.lua);
    luaopen_string(state.lua);
    luaopen_math(state.lua);

(add luaL_openlibs(state.lua), and delete luaopen_io(state.lua) )

I am curious to hear if this works for you.

Frank.
  P.S. Grüße aus Berlin :-)

**Comment by peti** [comment]
Hi FrMo,

I looked for a 0.5.1 release, but I couldn't find a tarball anywhere. Does that version number refer to the git head?

Liebe Grüße :-)
Peter

**Comment by FrMo** [comment]
Hi Peter,

sorry, i was actually talking about the git development head.
I have just commited some changes that should improve autoconf support for lua, and also fix the >2GB crash.
Gerald will probably merge in my latest changes in a few days; you can download a tarball here: https://github.com/FrMo/gravit/tarball/master

Thanks for reporting these problems!

Danke und viele Grüsse,
     Frank.

**Comment by peti** [comment]
Hi Frank,

you are right, the new version compiles fine with LUA 5.1. Thank you
very much for your efforts!

Take care,
Peter

**Comment by FrMo** [comment]
I think we can close this issue. gravit 0.6. can be build using LUA 5.0 or 5.1, and the configure script should be able to detect include paths and library names properly.

**Comment by peti** [comment]
Right, the issue is fixed, so I'll close this item. Thank you for your help!
