### ISSUE TITLE
Skybox

### ISSUE THREAD

**Issue by gak** [gak/gravit#2]

**Comment by gak** [comment]
From #39 @FrMo

> how about adding a feature to display some kind of "background image"?
> I am thinking of some stars and faint galaxies backgrounds, like the famous "hubble ultra deep field"

I was also considering using nebulas, galaxies, etc from ESO. ESO has a wide variety of images that are available to use freely as long as credit is given: http://www.eso.org/public/outreach/copyright.html

**Comment by FrMo** [comment]
I just did an 'intermediate merge' of the feature branch into develop, 
to have the setupCamera() function for my next feature (red-cyan anaglyph stereo).

**Comment by gak** [comment]
I added a skyboxrandom command in the last minute in 016879534921bcd905578fa8a6df5a88326ba476
