### ISSUE TITLE
change copyright notice

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#27]
Hi Gerald,

I have just noticed that gravit still has this message "Copyright 2003-2010 Gerald Kaszuba" in the bottom right corner.
For me, copyright sounds a little like "Try now, buy later". Actually, i would prefer that all my changes are under a public license, like GPL or whatever.

Would it be OK for you if we change the copyright message to be something more opensource-like, for example 
"Created 2003-2010 by Gerald Kaszuba", and maybe add  some fineprint like "powered by contributions from the open source community" ?

what do you think?

Frank.

**Comment by gak** [comment]
Frank,

I agree the copyright message should be changed to also cover yourself and other contributors.

Adding that extra text will probably make that copyright message appear to big. I'll have a think of what to do with it. I'm considering removing the copyright message and having a credits screen.

Gerald

**Comment by FrMo** [comment]
sounds good, thanks :-)

**Comment by gak** [comment]
I'll set it to "Copyright 2003-2011 Gravit Development Team", based on what I've seen other people do (as IANAL)

Will have a page on the website, and a section within gravit for the list authors.
