### ISSUE TITLE
Background panorama

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#39]
how about adding a feature to display some kind of "background image"?
I am thinking of some stars and faint galaxies backgrounds, like the famous "hubble ultra deep field".

It might be possible to put a large sphere around the center of view, with an image as texture;
this way the background would automaticially move when rotating the view.

**Comment by gak** [comment]
I've made an issue for this already albeit a not very descriptive one. I'll amend your comment to it so it is more descriptive.

Duplicate of #2
