### ISSUE TITLE
Detect number of processors

### ISSUE THREAD

**Issue by gak** [gak/gravit#4]

**Comment by FrMo** [comment]
would be very easy using OpenMP:

> int omp_get_num_procs(void);
>       Returns the number of processors available to the program.

or,depending on what you want to know:

> int omp_get_max_threads( )
>         Returns an integer that is equal to or greater than the number of threads 
>         that would be available if a parallel region were defined at that point in the code.

**Comment by FrMo** [comment]
When compiled with OpenMP multi-threading, gravit detects the number of threads automaticially.
--> we have a working solution now.

Doing the same for the older pthreads-based multithreading code is more complicated, and different on every OS.
--> too much extra effort.
