### ISSUE TITLE
make new agar GUI optional

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#48]
Agar is not available for everyone; as the new GUI is still an add-on to the old functionality, we should make the agar code optional.  (i.e. for ubuntu linux there is no pre-build agar, and compiling it yourself is problematic; 64bit - doubly so ;-) )

Changes needed:
- all agar code should depend on `#ifndef WITHOUT_AGAR`
    (so agar is still the default, but can be disabled)
- configure.in and Makefile.am should detect and properly handle the WITHOUT_AGAR case

**Comment by gak** [comment]
Good idea :)
