### ISSUE TITLE
Spread the news about 0.5.0

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#55]
- update change log (FrMo, gak)
- announce on google groups, freshmeat, and other places (gak ?)

**Comment by gak** [comment]
- Update the [Google+](https://plus.google.com/107724824744084522216/posts) page (which should update the [Gravit website](http://gravit.slowchop.com/))
- Post to the [Slowchop Studios blog](http://slowchop.com)
- Post to reddit to possibly get some attention
- Update the [Wikipedia page](http://en.wikipedia.org/wiki/Gravit)

**Comment by FrMo** [comment]
I just copied your google+ announcement to the gravit mailing list (google goups);
 to take the chance of getting people's attention during the weekend.

**Comment by gak** [comment]
Cool. I have updated the Wikipedia page too.

Will do reddit and blog once I get the app in the mac app store. (It was rejected)
