### ISSUE TITLE
Update the logo

### ISSUE THREAD

**Issue by gak** [gak/gravit#57]
- The icon in the app
- On Google+

@Frmo any other ideas?

https://github.com/gak/gravit/raw/f13dfc1521c3b15a8cb940e94603f57a80c7bad9/data/gravit.png

![logo](https://github.com/gak/gravit/raw/f13dfc1521c3b15a8cb940e94603f57a80c7bad9/data/gravit.png)

**Comment by gak** [comment]
I think all the logos have been updated in the source. Closing this one off.

**Comment by FrMo** [comment]
I think it looks good, more colorful than the old one!

**Comment by FrMo** [comment]
One late idea: could we give it rounded transparent corners (similar to the googe+ icon) ?
(if this is too much hassle, we could still improve the icon for 0.5.1....)

**Comment by gak** [comment]
Leave it for 0.5.1. I want to get Gravit released :)

**Comment by gak** [comment]
Added #67
