### ISSUE TITLE
configure is broken in the install step

### ISSUE THREAD

**Issue by gak** [gak/gravit#60]
Makefile.am refers to a path to install, but the script fails as "install" doesn't seem to allow installing directories.

The path involved is "gravit/data/skybox" which is referred to in Makefile.am.

**Comment by FrMo** [comment]
upps  ... will check

**Comment by FrMo** [comment]
@gak: please check if my last commit d49538c2334e752b461e59d3ab7efda4c39f154f fixes the problem.
We should keep in mind that this is a quick, ugly solution for 0.5.0. 

Whenever we want to distribute more skyboxes, they need to be added manually (to Makefile.am).

**Comment by gak** [comment]
That hack is perfectly fine for now. I'll verify it works soon.

**Comment by gak** [comment]
Seems to work.
