### ISSUE TITLE
smooth movements

### ISSUE THREAD

**Issue by FrMo** [gak/gravit#89]
currently, we directly apply mouse movements => view is directly jumping to the new position (view angle or zoom level).

It looks more natural if we make a "smooth" transition from the current position to the new view.
- temporally switch to 60 FPS (if possible)
- interpolate from the old to the new view
- smooth acceleration / decceleration instead of linear motion

**Comment by FrMo** [comment]
implemented. commit 48bc6684d1fcf621cbee68a921715176df3cba94

**Comment by gak** [comment]
@FrMo Please accept this 1 beer for your excellent work on Gravit. :) @changetip

**Comment by changetip** [comment]
Hi @frmo, you've been sent 5.4530 milli-bitcoins ($3.50) from @gak via ChangeTip. **[Collect it](https://www.changetip.com/collect/1947)**.

**[What's this?](https://www.changetip.com/tip-online/github)**

**Comment by FrMo** [comment]
Thanks :-))) Cheers!

(I'm quite busy on my job these days ... going to come back to gravit in April ...)
