### ISSUE TITLE
Problem with Gravit under Win 8.1

### ISSUE THREAD

**Issue by NiklasGoetz** [gak/gravit#92]
I wanted to use Gravit with my Win 8.1 computer (64-bit). The installation went normal, but as I started it for the first time, the curser disappeared and I couldn't press any buttons. However, the keyboard control (A/Z or on my European keyboard A/Y) was working normally.

**Comment by FrMo** [comment]
Hi Niklas,
thank you for reporting this problem.
I finally got my hands on a new laptop with Win8.1. Gravit is working for me, and I can see a mouse pointer. 
However, I noticed two problems:
1) when only using a touch device (touch pad or touch screen), it is nearly impossible to rotate the view.
2) Intel graphics driver: the Win8 driver has a new version number, but still shows the well-known problems in particlerendermode 1: text and GUI elements disappear.

To solve 1), we could allow rotation using the arrow keys (in the next version)
To solve 2), set "particlerendermode 2" in you gravit.cfg file

@NiklasGoetz : Do you still have the problems? If yes, you could help us to by adding the console output of gravit:
- Edit gravit.cfg ("customize gravit.cfg") and enable the line "echo 1" by removing the hash. 
- Then start gravit, try moving the view with the mouse, and quit. 
- You will find a file "stdout.txt" next to gravit.exe .
- Add the content here as a comment

Thank you,
  Frank.

**Comment by NiklasGoetz** [comment]
I've changed the gravit.cfg as you said, but it doesn't want to work... I cant't find stdout.txt anywhere. But I've found out that the mouse works well, I just can't see the pointer.

However, I tryed the second solution, the interface changed.

**Comment by FrMo** [comment]
Seems that this was a problem with particlerendermode 1 (intel corei graphics?).
In general, gravit works on windows  8 and windows 8.1
