### ISSUE TITLE
gravit --help, --version, etc. do not print anything

### ISSUE THREAD

**Issue by thinred** [gak/gravit#97]
When I run gravit --help I get no output. It seems to me that "view.useStdout" should be set to 1, at least at the beginning when cmdline arguments are parsed.

**Comment by FrMo** [comment]
Hi @thinred , thanks for pointing this out.
Could you check if commit 4f6133f8a8c2ade2cf92a197271de1f78ef1bd65 fixes the problem?

**Comment by thinred** [comment]
I compiled develo branch and it indeed works. Thanks.
